services:
  datum_gateway:
    # build: .
    image: signalorange/datum-gateway:latest
    ports:
      - "3333:3333"
    volumes:
      - ./config:/config
    environment:
      - BITCOIN_RPC_URL=http://bitcoin-node:8332
    depends_on:
      - bitcoin-node

  bitcoin-node:
    image: btcpayserver/bitcoinknots:latest
    volumes:
      - ./bitcoin-data:/home/bitcoin/.bitcoin
    command:
      -printtoconsole
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcauth=user:hash
